### ISSUE TITLE
Warn users if username, tenant_id pair changes during authentication

### ISSUE THREAD

**Issue by lekhajee** [rackerlabs/mimic#146]
If you authenticate once using a tenantId / username pair in your Identity request, and then you authenticate again later with the same username but a different tenantId, you'll get the first tenantId back, forever.  If you authenticate without using a tenantId at all on your first authentication request, you'll get one randomly generated, and subsequent requests will give back that randomly generated one.

The Identity mimic should at least log an error if the request includes an incorrect tenantId that doesn't match its existing idea of what the tenant should be.

**Comment by glyph** [comment]
Huh, I edited the description but it's still @lekhajee's picture next to it.  Github probably shouldn't let me put words in someone else's mouth like that, project owner or not :).

**Comment by cyli** [comment]
I was originally going to suggest that maybe we should not make usernames unique across all tenants, but apparently at least Rackspace does not seem to allow duplicate usernames across different tenants.

I believe if the wrong `tenantName`/`tenantId` is passed in the user auth section, identity returns a 401 Unauthorized?  Mimic can probably do the same.

**Comment by glyph** [comment]
Fixed by #154

**Comment by glyph** [comment]
> Rackspace does not seem to allow duplicate usernames across different tenants

Just for future reference... although lots of examples show identity authentication including a tenant ID, in fact, all you need (as on mycloud.rackspace.com) is a username and password, which means the username needs to be a globally unique lookup key.

Personally at least I have no idea why the tenant ID is ever included, I've never seen an explanation of what including it in auth does :).

**Comment by ksheedlo** [comment]
@glyph Including the tenant ID is necessary in the case of multiple clients. For instance, I have Cloud Intelligence and an API client that runs from the command line. I can't control the tenant ID that Intelligence uses - it's my Rackspace tenant ID and is not easy to change. The only way for both clients to see the same data is for me to configure the API client to use my Rackspace tenant ID.
