### ISSUE TITLE
stop setting Request.defaultContentType

### ISSUE THREAD

**Issue by glyph** [rackerlabs/mimic#202]
I think there was some confusion around this being specific to an individual file, rather than a temporary (and gross) hack to make a specific change.  We should be careful to set the content type in each response.  If copy/pasting the lines of code to do `json.dumps` and `setHeader` are tedious, we should make a decorator that combines it with `route`, perhaps, to avoid duplication, but we shouldn't manipulate global state.

**Comment by cyli** [comment]
Related to #40.  Please close out both if the decorator is created.
