### ISSUE TITLE
"sequence" behavior for server creation (hopefully generalizable for other things)

### ISSUE THREAD

**Issue by glyph** [rackerlabs/mimic#204]
Sometimes you need a server creation to intermittently fail in a deterministic way.

One way you can do this right now is to specify a failure behavior and then delete the behavior.  However, this will not give you an opportunity to delete the behavior between calls if the system under test is making calls close together with no blocking interaction with your test suite in between them.  (For example, a `for` loop that boots 10 servers in a row without even waiting for responses.)

We can implement this by having a `sequence` behavior, whose description takes some JSON that describes an array of *other* behaviors.  Let's take the example of a creation behavior that alternately fails with a 500 and then a 404, over and over again forever.

```json
{
    "name": "sequence",
    "parameters": {
        "behaviors": [
            {
                "name": "fail",
                "parameters": {
                    "code": 500,
                    "message": "lol"
                }
            },
            {
                "name": "fail",
                "parameters": {
                    "code": 404,
                    "message": "wut"
                }
            }
        ],
        "repeat": true
    }
}
```

We should also add a specifically-named `default` behavior so that it can be interleaved.  For example, a server that fails every other time it is created, forever, could look like this:

```json
{
    "name": "sequence",
    "parameters": {
        "behaviors": [
            {
                "name": "fail",
                "parameters": {
                    "code": 500,
                    "message": "lol"
                }
            },
            {
                "name": "default",
                "parameters": {}
            }
        ],
        "repeat": true
    }
}
```

When `"repeat"` is set to `false`, you instead go back to the default behavior after the last behavior described in the sequence's list of behaviors is executed.  So this creation behavior would fail 3 times, then succeed forever after:

```json
{
    "name": "sequence",
    "parameters": {
        "behaviors": [
            {
                "name": "fail",
                "parameters": {
                    "code": 500,
                    "message": "lol"
                }
            },
            {
                "name": "fail",
                "parameters": {
                    "code": 500,
                    "message": "lol"
                }
            },
            {
                "name": "fail",
                "parameters": {
                    "code": 500,
                    "message": "lol"
                }
            }
        ],
        "repeat": false
    }
}
```

**Comment by glyph** [comment]
This may need some refactoring so that created behaviors can be aware of themselves as registered in a particular `BehaviorRegistry` so that the "repeat" behavior can remove itself.

**Comment by cyli** [comment]
Can we close this ticket, since we have the repeat behavior for now?  Was there anything else we wanted to add to this behavior?

**Comment by glyph** [comment]
I think we're good!
