### ISSUE TITLE
Support CLB Bulk Delete

### ISSUE THREAD

**Issue by radix** [rackerlabs/mimic#213]
http://docs.rackspace.com/loadbalancers/api/v1.0/clb-devguide/content/DELETE_bulkDeleteNodes_v1.0__account__loadbalancers__loadBalancerId__nodes_Nodes-d1e2173.html

Basically, DELETE /.../nodes?id=a&id=b&id=c

**Comment by radix** [comment]
and some notes on undocumented/misdocumented stuff:

- pretty sure the response is 202, not 200
- error handling is really weird, and we're going to have to figure out exactly which errors take precedence.
  - if any nodes don't exist, I think 400 is returned for the whole thing and NO nodes are deleted
  - also 422 is a code that you can get if you're hitting it at the wrong time, though maybe we don't have to support that right now
  - bodies are returned with error messages

This is gonna take some serious exploration to determine real semantics

**Comment by radix** [comment]
confirmed: when bulk-deleting and one of the nodes is not deletable, `400` is returned and no nodes are deleted. The content of the response is like so:

```
{"validationErrors":{
    "messages": ["Node ids 100 are not a part of your loadbalancer"]},
 "message":"Validation Failure",
 "code":400,
 "details":"The object is not valid"}
```

(reformatted)

**Comment by radix** [comment]
oh, and to demonstrate the formatting when there are _multiple_ bad nodes passed:

```
{"validationErrors":{"messages":["Node ids 100,200 are not a part of your loadbalancer"]},"message":"Validation Failure","code":400,"details":"The object is not valid"}
```

**Comment by masthalter** [comment]
Hello Christopher,
Thank you for your feedback.

I have added additional information in the LB Developer Guide about what occurs in the case when you try to delete load balancers or nodes that cannot be deleted due to their current status. Please refer to sections 4.1.3 and 4.4.3.

I also added a new section 3.10.2 for API Errors.

Regards,

Mike

**Comment by glyph** [comment]
Thanks for adding that documentation, Mike!  And thanks for providing us the reference here :).

**Comment by cyli** [comment]
@masthalter Thank you for adding the documentation!  I see a sentence about 400:BadRequest in both section 4.1.3 and 4.4.3.

I notice that the documentation still says that the operation returns no response body though, and while that may be accurate for 200 operations, I was wondering if it was possible to include sample 400 responses in the documentation?

We've had to figure out ways to trigger the bad responses so we know what they'd look like, and it'd really be useful to have examples of error messages in the documentation.

Thanks!

**Comment by masthalter** [comment]
I have added an example error response in section 4.4.3.2 for Bulk-delete nodes.

Regards,

Mike

**Comment by cyli** [comment]
@masthalter Thank you!  I had one more question - are there any other reasons (other than the node already being on the load balancer) that a node would fail to be added to a load balancer, or any other reasons (other than the node not being on the load balancer) that a node would fail to be removed from a load balancer?  (Actually fail, as opposed to the load balancer just being in PENDING_UPDATE.)

**Comment by the2hill** [comment]
@cyli The only other reasons, besides validation, would be internal (500) errors on either case.

**Comment by cyli** [comment]
@the2hill In that case, it would be a 500 error, not a 400 validation error (even on bulk actions?)

**Comment by the2hill** [comment]
@cyli Correct, besides validation, the system will throw 500 errors, whereas 400 is bad request/validation even for bulk operations. There could be any number of actual reasons the system failed and those are usually not displayed as they are an internal only message.

**Comment by cyli** [comment]
@the2hill Cool thank you!
