### ISSUE TITLE
Add a Cinder / Cloud Block Storage plugin

### ISSUE THREAD

**Issue by wallrj** [rackerlabs/mimic#218]
It'd be nice to be able to run tests against a simulated Cinder v1 API rather than interact with a real  (slow) OpenStack cluster.

Rackspace seem to only support the v1 API (correct?), so start with that I guess:
 * http://developer.openstack.org/api-ref-blockstorage-v1.html

And specifically, only the ``volumes`` part:
 * http://developer.openstack.org/api-ref-blockstorage-v1.html#volumes-v1

Which should be enough for us to test https://github.com/ClusterHQ/flocker/pull/1314 and followup issues.

**Comment by glyph** [comment]
You're absolutely right, this is definitely something we should do. Thanks for filing the issue, @wallrj, glad to see you here :).

**Comment by wallrj** [comment]
#489 Added support for Cinder V2 ``list(detailed=False)``, which is actually pretty useful.

**Comment by glyph** [comment]
@wallrj should this issue be closed, theN?

**Comment by wallrj** [comment]
Yep, there is now a partial cinder plugin and this issue is too broad.
The missing endpoints can be added in a series of smaller issues.
Possibly Cinder v1 too, since that's all Rackspace provide (sadly).
