### ISSUE TITLE
Nova control plane api missing in the service catalog

### ISSUE THREAD

**Issue by lekhajee** [rackerlabs/mimic#237]
When one runs mimic using `twistd mimic` it does not load the control plane api for nova.

**Comment by glyph** [comment]
I guess nobody has tried to use this yet? @cyli - didn't autoscale need behaviors for something?

**Comment by glyph** [comment]
I'm going to assume that otter needs this for testing, so I'll add the label.

**Comment by cyli** [comment]
No one has used this yet, no.  But yes we will need this.

**Comment by cyli** [comment]
#236 fixes this :)
