### ISSUE TITLE
Replace characteristic with attrs

### ISSUE THREAD

**Issue by lvh** [rackerlabs/mimic#241]
Original ask: https://github.com/rackerlabs/mimic/pull/239/files#r29543698

This is an umbrella issue for filing all of the individual use cases.

On my current checkout of master, I get:

```
➜  mimic git:(identity-session) ag --files-with-matches --python characteristic                                                                                           08:52:21
mimic/model/behaviors.py
mimic/model/nova_objects.py
mimic/rest/nova_api.py
mimic/rest/swift_api.py
mimic/rest/rackconnect_v3_api.py
mimic/session.py
mimic/test/test_rackconnect_v3.py
setup.py
```

Therefore, the TODO is to replace the use of characteristic with attrs in:

- [ ] Shared logic: `mimic/model/behaviors.py` and `mimic/session.py`
- [ ] Nova, specifically: `mimic/model/nova_objects.py` and `mimic/rest/nova_api.py`
- [ ] `mimic/rest/swift_api.py`
- [ ] RackConnectV3, specifically: `mimic/rest/rackconnect_v3_api.py`, `mimic/test/test_rackconnect_v3.py`
- [ ] cloud load balancers: `mimic/model/clb_objects.py`

Once all of these are done and no new ones have been introduced:

- [ ] Remove the dependency from setup.py
- [ ] Remove the dependency requirements.txt

**Comment by BenjamenMeyer** [comment]
@glyph @lvh in one of my recent branches from master I did a "grep characteristic * -Rn" and didn't find anything - even done at the project root. Would that mean this is closed?

**Comment by glyph** [comment]
@BenjamenMeyer Yep - as of 7d09acc5efbf196008bfa456caf9ee462d0e24dc.  Thanks for spotting this!

**Comment by glyph** [comment]
( #543 closed this )
