### ISSUE TITLE
Make behavior injection a real REST interface

### ISSUE THREAD

**Issue by cyli** [rackerlabs/mimic#271]
- [x] When a behavior is specified, provide an ID for it.
- [ ] Allow listing of existing behaviors
- [x] Be able to delete behaviors by ID

Otherwise if Mimic isn't restarted, behaviors can persist across test runs.

**Comment by cyli** [comment]
Note - my plan is to turn the register creation behavior/list creation behavior/delete creation behavior into a decorator (???), so that people don't have to write all these endpoints again from scratch for other plugins' control planes.  So it'd look something like:

```
@behaviors({"creation": server_creation_event,
                      "deletion": server_deletion_event})
class NovaBehaviorControl(object):
    "pass"
```

This would be the bottom-level Twisted resource, that adds endpoints like `/<event-name>/<behavior_id>` only.  This way the control plane handles the rest of the URL routing.

**Comment by glyph** [comment]
That looks like a good plan to me.

**Comment by cyli** [comment]
@glyph Thoughts on providing a standard suite of tests?  Or should the tests on the utility function be good enough?

**Comment by glyph** [comment]
@cyli Already typing that - github needs a better way to do multi-part replies :smile:

**Comment by glyph** [comment]
> Suggestions/thoughts? I am not sure how to provide standard tests that work with all kinds of plugins and failures, though...

The way to do this is to parameterize the test suite with the parts that vary per suite.  So for example, in this case, one thing that differs per system is the "create some JSON for a valid criterion" step, and another is the "discover the control plane endpoint" step.  Have a function that creates a `TestCase` class where you have to give it an object that knows how to create some valid criterion, and then has a `test_` method which creates a valid criterion, discovers the control plane endpoint, then, in test code common to all backends, POSTs to the behaviors/creation endpoint.

Does that make sense?

**Comment by cyli** [comment]
@glyph Wondering if this should just be a partially-implemented class that others can subclass?

**Comment by glyph** [comment]
@cyli sigh; I wrote out that whole paragraph without saying "inheritance" or "subclass" once. but yeah, that's one way to do it.

**Comment by cyli** [comment]
@glyph Yes yes I know.  :)  I just want to make sure that all the FQDNs for the test methods are right, and not some anonymous `TestCase`

**Comment by glyph** [comment]
A decorator, maybe?

**Comment by cyli** [comment]
Eh, listing is not done, but we can probably close this ticket since we can create and delete.  We can add an issue for listing if necessary later - not sure it's that useful.
