### ISSUE TITLE
drop python 2.6 support

### ISSUE THREAD

**Issue by glyph** [rackerlabs/mimic#318]
The final release of Python 2.6 was Python 2.6.9 https://www.python.org/download/releases/2.6.9/ on October 9, 2013.  Since then - at this writing, for almost 2 years - Python 2.6 has been officially retired and is now unsupported.

[Twisted is moving to drop Python 2.6 support](https://twistedmatrix.com/pipermail/twisted-python/2015-June/029549.html) because it is a maintenance burden, and it is easier to span the 2.x / 3.x gap when the only 2.x release you have to worry about is 2.7, and the Twisted development team does not wish to encourage the use of unsupported and therefore potentially insecure software.

If Mimic has users who are using python 2.6 they should speak up so that we can advocate for Twisted to continue supporting it; otherwise we should prepare to turn off the Travis builders and announce that we're 2.7-only.

**Comment by sam-falvo** [comment]
When should any Python 2.6 users speak up by?  E.g., what is the deadline for deciding?  (Personally, I +1 this proposal.)

**Comment by glyph** [comment]
Twisted has at least one more release left with 2.6 support, which will probably go out in somewhere between one and three months.  HI @hawkowl.  Any interested parties should pipe up before that goes out, because 2.7-only code might start landing as soon as it's done.  That said, *probably* it will still kinda work for a while once the buildbots are gone, so as long as you get in before the next release *after* that with a really compelling reason, Twisted could restore 2.6 support for some amount of time.

**Comment by ksheedlo** [comment]
+1 for dropping support for old things!

**Comment by hawkowl** [comment]
The Twisted 15.3 release is pegged for July.

**Comment by ksheedlo** [comment]
Twisted 15.3 has landed and no one so far has voiced disagreement. Can we move forward with this?

**Comment by glyph** [comment]
@ksheedlo - I guess we should.  Like Twisted, we should probably do a final release that supports 2.6, and then drop support.  I'll try to get to that in the coming week.

**Comment by hawkowl** [comment]
PURGE THE 2.6

**Comment by ksheedlo** [comment]
I'm going to cite this for each PR that fails because of 2.6 until it gets resolved.

**Comment by lekhajee** [comment]
The Ele team was running mimic on py26 last I checked. We have to make sure they have upgraded before we do this.

**Comment by lekhajee** [comment]
@jayofdoom suggested a great idea of printing a deprecation warning so we can warn users before we actually deprecate py26

**Comment by ksheedlo** [comment]
+1 for a deprecation warning.

I talked to MaaS this afternoon and Phoebe told me they don't use 2.6 anymore.
