### ISSUE TITLE
Support MaaS Audit Log

### ISSUE THREAD

**Issue by ksheedlo** [rackerlabs/mimic#377]
http://docs.rackspace.com/cm/api/v1.0/cm-devguide/content/GET_listAudits_audits_service-account.html

MaaS keeps a log of requests the user performed against their service. Intelligence uses this log to power a widget in the dashboard, which we want to test in Mimic. Log entries map roughly 1:1 to API requests and carry the following information:

- `id` - a UUID, presumably for the API transaction.
- `timestamp` - self explanatory
- `headers` - a hash of all the headers that were sent with the API call.
- `url` - the HTTP url that was used, for instance `/v1.0/123456/entities/enaBcDeFg/test-check`
- `app` - varies depending on the resource. The following apps exist, but may not be the complete set:
    - `agent_installers`
    - `alarms`
    - `checks`
    - `entities`
    - `notification_plans`
    - `notifications`
    - `rollups`
    - `suppressions`
- `query` - a hash of the query string parameters
- `txnId` - a long string including parts of the internal URL for MaaS, a timestamp, and other things. I would fake this with a number or generally some random string.
- `payload` - The HTTP request body, if any.
- `method` - The HTTP method
- `account_id` - The tenant ID
- `who` - I see this always come back as an empty string, don't know what it's for.
- `why` - Ditto.
- `statusCode` - The HTTP status code that was returned.

To implement this feature, we need to get the data, or a reasonable-looking fake, and stash it somewhere in case the user asks for it. I want to look at doing it with a decorator, as it would otherwise be a lot of boilerplate that potentially every new MaaS op needs to be aware of. @glyph what are your thoughts about this? Can we fit what's needed into our existing klein routes?

**Comment by ksheedlo** [comment]
cc @ynachiket

**Comment by ksheedlo** [comment]
One other notable point: Read-only operations (i.e., `GET`) do not create an entry in the audit log.

**Comment by ksheedlo** [comment]
Update: Added `agent_installers` app

**Comment by ynachiket** [comment]
@lekhajee lets sync up on this soon.
