### ISSUE TITLE
Prevent IP collision within a tenant

### ISSUE THREAD

**Issue by cyli** [rackerlabs/mimic#383]
Since IPs are randomly generated, they might collide with each other.

Autoscale is encountering an issue where, because the the tests are generating so many servers, one autoscale group is removing an IP from a CLB that belongs to one of its servers.

However, that IP also belongs to a different server created by a different test, and hence removing it from the CLB breaks the test.

We should probably have a function `ensure_unique` or something that takes callable which generates a random value, and compares it to a set of already-generated random values to ensure that it produces a unique value.

Autoscale only cares about collision within a single tenant, but probably this should be across all tenants to behave more like the cloud.

**Comment by glyph** [comment]
Thanks so much for diagnosing this, @cyli .

I think what we need here is just a non-repeating PRNG algorithm, rather than a random-then-test.

**Comment by glyph** [comment]
I derived the following non-repeating random number generator from [this blog post](http://preshing.com/20121224/how-to-generate-a-sequence-of-unique-random-integers/); I'm wondering if maybe it should even be a separate library on PyPI, since this problem (a random 32-bit number that will never repeat, i.e. for a random IP address) crops up from time to time…

```python
largest_32_bit_prime = 0xFFFFFFFB
limit =                0xFFFFFFFF

def permuteQPR(counter):
    if counter >= largest_32_bit_prime:
        return counter
    residue = (counter * counter) % largest_32_bit_prime
    if counter <= largest_32_bit_prime / 2:
        return residue
    else:
        return largest_32_bit_prime - residue

class NonRepeatingRandom(object):
    def __init__(self, mask, counter):
        self.mask = mask
        self.counter = counter

    def current(self):
        return permuteQPR(self.counter) ^ self.mask

    @classmethod
    def fromRandom(cls):
        import random
        rnd = random.SystemRandom()
        def random32bit():
            return rnd.randint(0, limit)
        return cls(random32bit(), random32bit())

    def __iter__(self):
        def tick():
            self.counter += 1
            if self.counter > limit:
                self.counter = 0
                return None
            return self.current()
        return iter(tick, None)
```
