### ISSUE TITLE
Add support for py3.0 to be able to have mimic under Openstacks global requirements

### ISSUE THREAD

**Issue by lekhajee** [rackerlabs/mimic#392]

**Comment by ksheedlo** [comment]
Can you explain what "have mimic under Openstacks global requirements" means?

**Comment by ksheedlo** [comment]
I'm for this if we have users asking for py3.0 support. I would be concerned about the maintenance burden of officially supporting more versions of Python, though. As far as OpenStack wanting to keep everything Python, let alone py3, I could care less.

**Comment by ksheedlo** [comment]
I assume you're talking about https://github.com/openstack/requirements.

In which case I think this is a reasonable objective and I'm :+1: for this issue. With the caveat that I'd prefer to see users consume Mimic through Docker or otherwise linking to it through runtime configuration. It's hard for me to think of a use case where it makes more sense to include Mimic in `requirements.txt` and importing the code directly.

**Comment by lekhajee** [comment]
@glyph : I understand the treq is not yet compatible with py3. Does that still hold true. We are very close to having mimic included in the OpenStack global requirements and the only thing keep us from it is py3 compatibility.

**Comment by glyph** [comment]
@lekhajee I am back at work on Monday and I can start making https://github.com/twisted/treq/issues/63 a priority :-).

Presumably Klein would need to port as well?

**Comment by glyph** [comment]
Filed https://github.com/twisted/klein/issues/86

**Comment by lekhajee** [comment]
@glyph : how is it going with porting treq and klein

**Comment by glyph** [comment]
@lekhajee It turns out that @hawkowl has already started work on both of these; there is a PR open in Treq https://github.com/twisted/treq/pull/110 and in Klein https://github.com/twisted/klein/pull/79 both of which are now linked from their respective issues.

**Comment by glyph** [comment]
Right now I'm just coming up to speed on those PRs (which need to be updated against master) and the related tickets in Twisted, but I think we can do some work this week to get everything landed and a release of everything should be coming soon after that.  But it sort of depends on me being awake and around at the same time as @hawkowl a lot this week :).

**Comment by glyph** [comment]
Twisted 15.5 release candidate is out, so we need to do treq and klein.

**Comment by glyph** [comment]
https://github.com/twisted/klein/pull/79 and https://github.com/twisted/treq/pull/110 landed so now we're just waiting for releases.

**Comment by glyph** [comment]
Fixed as of https://review.openstack.org/#/c/220268/
