### ISSUE TITLE
Create control plane endpoint for Valkyrie plugin and cleanout Auth API canned responses

### ISSUE THREAD

**Issue by tpboudreau-rackspace** [rackerlabs/mimic#457]
Changes introduced in PRs #444 and #454 (adding canned responses for the Identity API) and PRs #409 and #445 (adding a Valkyrie plugin) created an undesirable coupling between the Identity and Valkyrie API plugins.

These PRs landed with an explicit pledge by @tpboudreau-rackspace to (1) remove the included Valkyrie fixtures; (2) add a control plane mechanism to the Valkyrie API to load fixtures; and (3) remove the canned response fixtures from the Identity plugin that are tied to the Valkyrie plugin in favor of a control plane mechanism.

**Comment by glyph** [comment]
@tpboudreau-rackspace Thanks for creating this :). Would you mind creating separate issues for each of these three things?  Issues with an "and" in their name are always trouble if they need to land all at once.

**Comment by tpboudreau-rackspace** [comment]
Sorry for the delay on this @glyph.  Closed in favor of #467, #468, and #469.
