### ISSUE TITLE
docker build failed

### ISSUE THREAD

**Issue by nyasukun** [rackerlabs/mimic#505]
this Dockerfile is from python:2.7-onbuild.
However python:2.7-onbuild requires "requirements.txt."
It seems requirements.txt was deleted at this commit 76175faef4f5ec0385bd3bef8c6c2005ec2d98c9
Since this, docker build always failed.

In my environment, it is successful to build with creating a link "requirments.txt" to "requirements/production.txt."

**Comment by glyph** [comment]
Thanks for reporting this issue.  Clearly we need to be putting the docker build into our CI...

**Comment by nyasukun** [comment]
Is there any reason not to add requiments.txt as a link at root?

**Comment by glyph** [comment]
We have three options, as I see it:

1. A symlink, which would cause problems for Windows users,
2. A copy, which would work fine for Windows users, but create duplication,
3. Move the file, which means we manage requirements files inconsistently (some in `requirements/`, some not)

I guess 3. is probably the least-bad option.

**Comment by nyasukun** [comment]
I have another option:
* Modify Dockerfile to use the file under the ```requirments/```

see:
https://github.com/rackerlabs/mimic/compare/master...nyasukun:dockerfile_without_onbuild?expand=1

**Comment by glyph** [comment]
@nyasukun That looks pretty reasonable. Want to submit a PR?

**Comment by nyasukun** [comment]
@glyph Yes. I submitted a PR #507.

**Comment by derwolfe** [comment]
Would adding a docker build step on travis be sufficient for adding this to CI?

**Comment by glyph** [comment]
@derwolfe - those two things are bascially synonyms, so yes.

**Comment by derwolfe** [comment]
@glyph sorry, that question was a bit unclear on my part. What I meant was, is the only concern that the image builds or should there be some tests run against the image?

**Comment by glyph** [comment]
@derwolfe - oh. well it would be nice to just get the build, for starters :). but ideally it would be just like the Mac app build; build the image, run the tests in the context of the thing that was just built

**Comment by nyasukun** [comment]
@glyph It seems to be merged. Can you close this issue?

**Comment by glyph** [comment]
Oops, I guess the PR didn't have a "fixes" in its description.  The word "solves" is not similarly magic :)

**Comment by nyasukun** [comment]
oh. sorry. I'm new in github and travis.

**Comment by lvh** [comment]
... It seems like this should have been closed, so I'll go ahead and close it :)

**Comment by glyph** [comment]
Yep! Thanks for noticing, @lvh .
