### ISSUE TITLE
Cut a mimic release/upload to PyPi

### ISSUE THREAD

**Issue by derwolfe** [rackerlabs/mimic#599]
I'm working on a project that depends on the new `mimic.imimic.IAPIDomainMock` interface. As of right now, a version of mimic that surfaces this interface isn't available on pypi.

Please release a new version of mimic. Thanks!

(Also if there is anything I can do to help out, please tell me 😄 )

**Comment by glyph** [comment]
I'll try to get to it by Friday.  Maybe one of the things I can do here while I'm at it is give you PyPI access ;-)

**Comment by derwolfe** [comment]
Thanks! I'd happily have PyPI powers :-)

**Comment by glyph** [comment]
Oof. Not friday, then. Perhaps today? :)

**Comment by glyph** [comment]
Done. https://pypi.python.org/pypi/mimic/2.1.0

**Comment by glyph** [comment]
Closing this as fixed but please reopen if there are any issues with the release.

**Comment by derwolfe** [comment]
@glyph Thanks!

**Comment by glyph** [comment]
@derwolfe You're quite welcome! Please keep me in the loop as you have more requirements for that project.
