### ISSUE TITLE
Option to have OFFLINE CLB node created

### ISSUE THREAD

**Issue by manishtomar** [rackerlabs/mimic#629]
Currently, a CLB node created has ONLINE status. But there are [situations](https://github.com/rackerlabs/otter/issues/1870) where test wants to have a created node be OFFLINE and choose when to go ONLINE. This is not feasible through regular API and will need behavior API. To be clear it will need customized "Add Node" behavior similar to how it there for [Nova create server](https://github.com/rackerlabs/mimic/blob/master/mimic/model/nova_objects.py#L383-L665). I am thinking of following PRs:

- [ ] Provide default "add node" behavior and have REST call this
- [ ] Provide LB_ID based "add node" behavior that chooses the status of the created node

Let me know if this makes sense and I will start working on this.

**Comment by manishtomar** [comment]
@glyph thoughts?

**Comment by glyph** [comment]
yes

**Comment by manishtomar** [comment]
After discussing we concluded that custom "add node" behavior is currently not required since CLB's default behavior is to create node with OFFLINE status when health monitor is enabled. I'll be making that change in mimic. And also provide change node status control plane API.
