### ISSUE TITLE
Cut a mimic release/upload to PyPi

### ISSUE THREAD

**Issue by wallrj** [rackerlabs/mimic#698]
It'd be great to have a new Mimic release.
I'm waiting for a package that includes https://github.com/rackerlabs/mimic/pull/668 and https://github.com/rackerlabs/mimic/pull/669.
For the time being Flocker relies on a forked version of Mimic.

See: 
 * Flocker Issue: https://clusterhq.atlassian.net/browse/FLOC-4513
 * Previous release: https://github.com/rackerlabs/mimic/pull/607

I'll help out if you like.

**Comment by glyph** [comment]
https://pypi.python.org/pypi/mimic/2.2.0
