### ISSUE TITLE
make a mac application bundle out of mimic

### ISSUE THREAD

**Issue by glyph** [rackerlabs/mimic#88]
It would be neat to distribute a little downloadable self-contained application that contained a Python interpreter, Mimic, and all of its dependencies (with py2app) that allowed users to do development and experimentation against the various mocked APIs.

If we do this, later we could also have a little GUI representation, like a hierarchical menu, of all of your provisioned servers... but that would definitely be a separate issue.

**Comment by cyli** [comment]
Looks like this has been done.

**Comment by derwolfe** [comment]
Yes :-) - glyph's PR that closed it is #191

**Comment by cyli** [comment]
Thanks for all your hard work @derwolfe!

**Comment by glyph** [comment]
Oops - thanks for the ticket gardening @cyli !

**Comment by derwolfe** [comment]
@cyli - You're welcome! Thanks for letting me work on it!
